version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    allow:
      - dependency-name: "lodash"
      - dependency-name: "@jscutlery/semver"
      - dependency-name: "@ledgerhq/hw*"
      - dependency-name: "@meteorwallet/sdk"
      - dependency-name: "@walletconnect/qrcode-modal"
      - dependency-name: "@walletconnect/sign-client"
      - dependency-name: "better-sqlite3"
      - dependency-name: "big.js"
      - dependency-name: "buffer"
      - dependency-name: "copy-to-clipboard"
      - dependency-name: "is-mobile"
      - dependency-name: "near-api-js"
      - dependency-name: "ngx-deploy-npm"
      - dependency-name: "qrcode"
      - dependency-name: "react-qr-code"
      - dependency-name: "regenerator-runtime"
      - dependency-name: "rxjs"
      - dependency-name: "tslib"
      - dependency-name: "@types/big.js"
      - dependency-name: "@types/gh-pages"
      - dependency-name: "@types/qrcode"
      - dependency-name: "@types/w3c-web-hid"
      - dependency-name: "@types/w3c-web-usb"
      - dependency-name: "@walletconnect/types"
      - dependency-name: "gh-pages"
